[build]
publish = "public"
command = "zola build"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.21.0"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=63072000; includeSubdomains"
# To update the style-src value, run one of the following commands:
# linux (coreutils)
# cksum --algorithm sha256 --base64 < templates/style.css.html | cut -d' ' -f 4
# macOS (should also work on linux if xxd is installed)
# shasum --algorithm 256 templates/style.css.html | cut -d' ' -f 1 | xxd -r -p | base64
# if nothing else works
# openssl dgst -sha256 -binary < templates/style.css.html | openssl enc -base64
# and paste the output after sha256-
Content-Security-Policy = "default-src 'none'; img-src 'self'; object-src 'none'; script-src 'none'; style-src 'sha256-PKsAyc2CAbvt1axikIx7gOr3bSn047az3mVPNOp94EA='; form-action 'none'; base-uri 'self'; frame-ancestors 'none'"
Cross-Origin-Resource-Policy = "same-site"
Cache-Control = '''
  max-age=300,
  s-maxage=86400,
  stale-while-revalidate
'''
