name = "Bear"
description = "Bear blog theme"
license = "MIT"
homepage = "https://codeberg.org/alanpearce/zola-bearblog"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = "https://zola-bearblog.alanpearce.eu/"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
date_format = "%d %b, %Y"
webserver_sends_csp_headers = false

[extra.table_of_contents]
show = false
max_level = 6
visible_on_load = true

[author]
name = "Alan Pearce"
homepage = "https://alanpearce.eu"

[original]
author = "janraasch"
repo = "https://github.com/janraasch/hugo-bearblog/"
homepage = "https://www.janraasch.com"
